apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisbank-dg-deployment
spec:
  selector:
    matchLabels:
      app: redisbank-dg
  replicas: 1
  template:
    metadata:
      labels:
        app: redisbank-dg
    spec:
      containers:
      - name: redisbank-dg
        image: < your image >
        imagePullPolicy: Always
        ports:
        - name: redisbank-dg
          containerPort: 8080
        env:
        - name: SPRING_REDIS_HOST
          value: "<Enter your host>"
        - name: SPRING_REDIS_PORT
          value: "<Enter your port>"
        - name: SPRING_REDIS_PASSWORD
          value: "<Enter your password>"
        #- name: SPRING_PROFILES_ACTIVE
        #  value: "tls"